default_language_version:
  python: python3.12

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    -   id: black
        language_version: python3.12
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
    # Run the linter.
    -   id: ruff
        args: [ --fix ]
    # Run the formatter.
    -   id: ruff-format
