# Generated by Django 4.0 on 2022-09-22 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name des Accounts')),
                ('bank', models.CharField(max_length=255, verbose_name='Name der Bank')),
                ('owner', models.CharField(max_length=255, verbose_name='Name des Besitzers')),
                ('current_amount', models.FloatField(default=0.0, verbose_name='Kontostand')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kategorie')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Betrag')),
                ('recipient', models.CharField(max_length=255, verbose_name='Empfänger')),
                ('subject', models.CharField(max_length=255, verbose_name='Buchungsinformation')),
                ('full_subject_string', models.TextField(verbose_name='gesamte Buchungsreferenz')),
                ('date_issue', models.DateField(verbose_name='Buchungstag')),
                ('date_booking', models.DateField(verbose_name='Wertstellungstag')),
                ('bank_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.bankaccount', verbose_name='Bank')),
                ('categories', models.ManyToManyField(blank=True, to='accounting.Category', verbose_name='Kategorien')),
            ],
        ),
    ]
