# Generated by Django 4.0 on 2022-09-22 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Betrag')),
                ('recipient', models.CharField(max_length=255, verbose_name='Empfänger')),
                ('subject', models.CharField(max_length=255, verbose_name='Buchungsinformation')),
                ('full_subject_string', models.TextField(verbose_name='gesamte Buchungsreferenz')),
                ('date_issue', models.DateField(verbose_name='Buchungstag')),
                ('date_booking', models.DateField(verbose_name='Wertstellungstag')),
            ],
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='current_amount',
            field=models.FloatField(default=0.0, verbose_name='Startkontostand'),
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belongs_to', to='accounting.bankaccount', verbose_name='Bank'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='categories',
            field=models.ManyToManyField(blank=True, to='accounting.Category', verbose_name='Kategorien'),
        ),
    ]
