# Generated by Django 3.2.23 on 2024-02-12 16:33

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0004_bankdepot_depotasset_depotassettransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="depotasset",
            name="last_update",
            field=models.DateField(
                default=datetime.date(2024, 2, 12), verbose_name="Letztes Update"
            ),
        ),
    ]
