# Generated by Django 3.2.23 on 2024-05-17 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_transaction_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
        migrations.AlterField(
            model_name='depotasset',
            name='last_update',
            field=models.DateField(default=datetime.date(2024, 5, 17), verbose_name='Letztes Update'),
        ),
    ]
