# Generated by Django 3.2.23 on 2024-05-29 08:42

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0008_auto_20240517_1248"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Enddatum"),
        ),
        migrations.AddField(
            model_name="contract",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Startdatum"),
        ),
        migrations.AlterField(
            model_name="depotasset",
            name="last_update",
            field=models.DateField(
                default=datetime.date(2024, 5, 29), verbose_name="Letztes Update"
            ),
        ),
    ]
