# Generated by Django 3.2.23 on 2024-11-21 13:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20240529_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depotasset',
            name='last_update',
            field=models.DateField(default=datetime.date(2024, 11, 21), verbose_name='Letztes Update'),
        ),
        migrations.CreateModel(
            name='ContractFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contract_files', verbose_name='Datei')),
                ('filename', models.CharField(max_length=255, verbose_name='Dateiname')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_of', to='accounting.contract', verbose_name='Vertrag')),
            ],
        ),
    ]
